version: '3.3'
services:
  dev-ssl:
    build:
      context: .
      dockerfile: docker/dev-ssl/Dockerfile
    restart: "no"
    volumes:
      - ./data/ssl/certs:/etc/ssl/certs
      - ./docker/dev-ssl/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - DOMAIN

  pier-buoy:
    image: nginx:1.13.12-alpine
    restart: always
    volumes:
      - ./data/ssl/certs:/etc/ssl/certs
      - ./docker/web-proxy/nginx/conf.d:/etc/nginx/conf.d
      - ./:/etc/nginx/map.d
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    external:
      name: pier-buoy
