version: '3.3'
services:
  pier-buoy:
    image: nginx:1.12.1-alpine
    restart: always
    volumes:
      - ./docker/web-proxy/nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "80:80"

networks:
  default:
    external:
      name: pier-buoy
