version: '3.3'
services:
  dev-ssl:
    image: lightster/dev-ssl:0.1.0
    restart: "no"
    volumes:
      - ./data/ssl/certs:/cert
    environment:
      DOMAIN: ${DOMAIN:-b.com}

  buoy:
    image: kelvineducation/nginx-envsubst:0.2.1
    restart: unless-stopped
    volumes:
      - ./data/ssl/certs:/etc/ssl/certs
      - ./docker/web-proxy/nginx/conf.d/home.conf:/etc/nginx/conf.d/home.conf.envsubst
      - ./:/etc/nginx/map.d
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN:-b.com}

networks:
  default:
    external:
      name: buoy
